date: 2019-08-05 15:15
app: markdown
layout: 'post'
title: 'Lustre故障跟踪之ldlm_resource_complain'
tags: Lustre

今天运维同事反馈过来一个问题，有个集群的客户端重启后无法挂载Lustre，报错信息如下：
```bash
[root@host-xx-xx-xx-xx ~]# mount.lustre -o localflock xx.xx.xx.202@o2ib:xx.xx.135.201@o2ib:/shlfs /mnt/lustre/
mount.lustre: mount 10.5.135.202@o2ib:10.5.135.201@o2ib:/shlfs at /mnt/lustre failed: Input/output error
Is the MGS running?
```